### ISSUE TITLE
User data is not migrated from legacy version

### ISSUE THREAD

**Issue by alvarogzp** [mozilla/lightbeam-we#208]
I have just had Lightbeam updated to the webext version, and the first run web page appeared. When I clicked on the lightbeam icon, all the visited sites I previously had there just had disappeared!

If a user data migration is possible from a legacy addon implementation to the webext one (as others, like [uBlock origin](https://github.com/gorhill/uBlock/wiki/Firefox-WebExtensions), have done), I think it should be taken into account, as it might be disappointing for users to lost all the data from an addon whose purpose is to analyze data across a long timespan, just because of an update of the addon.

**Comment by jonathanKingston** [comment]
Unfortunately due to the huge changes we made in this extension we were not able to change the data over.

We took this approach for several reasons:
- In making this extension we found several bugs in how the previous addon was capturing data which invalidated the data itself
- The structure used here is vastly different, designed firstly for performance
- Given our tight deadlines we took the view that as this captured data doesn't stay forever anyway users can build this back up again.
  - The current extension removes a few features that storage was used for like blocking individual sites also. These features might come back in the future but probably not in their initial form.

We understand this is disappointing but given the huge changes in the display and validity of the data itself, I think it makes sense to start fresh so users can evaluate with the new gathering methods. The previous data simply didn't match up to how we have it now.

We have many things to fix along the way, one of them is data invalidation next as we believe the extension should only store a 30 or 60 day window into your web browsing experience. We are going to evaluate what that period of time should be and adjust accordingly.

Thanks for the bug and again I am sorry. I'm going to close this as it's not possible to fix this now the extension has been pushed.

**Comment by alvarogzp** [comment]
Ok, thanks for the explanation! And for the extension!

**Comment by jonathanKingston** [comment]
Hopefully you will find it performs much better 👍 

Also it was @biancadanforth and @princiya that did all the hard work, I'm just the support monkey.

**Comment by alvarogzp** [comment]
Yes, it seems to run more smoothly, although I still have very few sites. Good job!
