### ISSUE TITLE
Make vars dynamic

### ISSUE THREAD

**Issue by jonathanKingston** [mozilla/lightbeam-we#65]
From #61

Make `<var` and `<time>` elements dynamic from storage data.

**Comment by biancadanforth** [comment]
@jonathanKingston Here is some brainstorming about how to go about this:

**How to determine each value:**
1. Data gathered since
 - If there's nothing in the store, (i.e.: if it's the first run of the app or if the user clicks 'Reset Data'), update this value to be blank or '--'
 - else, the value is equal to the date of the oldest `website` object in the `websites` table in IndexedDB.
 - only needs to be updated on init/'Reset Data'
2. You have visited (# visited sites)
- If there's nothing in the store, this value is 0.
- else, the value is equal to the number of `website` objects in store with a `firstParty` of `true`.
- Should be updated with each new first party addition to the `websites` store
3. You have connected with (# third party sites)
2. You have visited (# visited sites)
- If there's nothing in the store, this value is 0.
- else, the value is equal to the number of `website` objects in store with a `firstParty` of `false`. AKA the total number of websites in the store minus those that are first parties.
- - Should be updated with each new third party addition to the `websites` store

**Where to store this:**
Make a separate store to the `websites` one we currently have, since the structure of the data for these dynamic variables is different.

**Comment by jonathanKingston** [comment]
We could instead populate the page async based on the current data in store
when the find result returns.

Changing store to ensure we have first capture time would potentially be
easier and useful for removing old data later.

**Comment by princiya** [comment]
> How to determine each value:
Looks good to me.

> Where to store this:
I don't think you need a separate store. We already have this information in our store.
We can have a separate page-script like `viz.js`, something like `vars.js` (name can be changed).

*`var.js`*
```
const vars = {
 date: '',
 firstParty: '',
 thirdParty: '',

 init() {
  // populate the above vars by querying the store 
 }
}
```

The way `viz.js` gets input about websites from store, `vars.js` needs to be populated too.
The only thing to take care of is how to refresh the `visited` count when new first/third parties are added.
We might need a listener which constantly checks for new values and updates them.

**Comment by jonathanKingston** [comment]
I think these vars that princiya mentions could be stored and updated in
lightbeam.js

Also to be clear "websites" should be able to store this data.

**Comment by biancadanforth** [comment]
@jonathanKingston Why wouldn't we want to keep the data in a separate store from `websites`? The UI variables don't have any of the same keys as the `website` objects in `websites`.

Here is the structure of the `websites` database currently:

```javascript
  makeNewDatabase() {
    this.db = new Dexie('websites_database');
    this.db.version(1).stores({
      // store: 'primaryKey, index1, index2, ...'
      websites: 'hostname, dateVisited, isVisible, firstParty'
    });
    this.db.open();
  },
```

Also, can you explain a little more what you mean when you say...:

> We could instead populate the page async based on the current data in store when the find result returns.

> Changing store to ensure we have first capture time would potentially be easier and useful for removing old data later.
